### Send POST request with body as parameters
POST http://localhost:8080/sendSingleMessage
Content-Type: application/x-www-form-urlencoded

message="Hello, Rabbit!"


### Send POST request with body as parameters
POST http://localhost:8080/sendBatch
Content-Type: application/x-www-form-urlencoded

message="Hello, Rabbit!"&batchSize=10
